# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ObserveTraits.protobuf
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16ObserveTraits.protobuf\x12\x08nest.rpc\"g\n\x0eObserveRequest\x12\x12\n\x07version\x18\x01 \x01(\r:\x01\x32\x12\x17\n\tsubscribe\x18\x02 \x01(\x08:\x04true\x12(\n\x06\x66ilter\x18\x03 \x03(\x0b\x32\x18.nest.rpc.ResourceFilter\"9\n\x0eResourceFilter\x12\x12\n\ntrait_type\x18\x01 \x01(\t\x12\x13\n\x0bresource_id\x18\x02 \x01(\t')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ObserveTraits.protobuf_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _OBSERVEREQUEST._serialized_start=36
  _OBSERVEREQUEST._serialized_end=139
  _RESOURCEFILTER._serialized_start=141
  _RESOURCEFILTER._serialized_end=198
# @@protoc_insertion_point(module_scope)
