# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/weave/trait/label_settings.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database

_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b"\n$proto/weave/trait/label_settings.proto\x12\x17weave.trait.description"
    b'\"\x1f\n\x12LabelSettingsTrait\x12\t\n\x05label\x18\x01 \x01(\tb\x06proto3'
)

_LABELSETTINGSTRAIT = DESCRIPTOR.message_types_by_name["LabelSettingsTrait"]
LabelSettingsTrait = _sym_db.RegisterMessage(_LABELSETTINGSTRAIT)

